apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-kubernetes-config
data:
  config: |
    apiVersion: v1
    clusters:
    - cluster:
        server: https://172.16.3.82:6443
       # certificate-authority: /root/.kube/ca.crt
      name: kube01
    contexts:
    - context:
        cluster: kube01
        user: root
      name: kube01
    current-context: kube01
    kind: Config
    preferences: {}
    users:
    - name: root
      user:
       # client-certificate: /root/.kube/apiserver.crt
       # client-key: /root/.kube/apiserver.key
    - name: spinnaker-service-account
      user:
       token: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InNwaW5uYWtlci1zZXJ2aWNlLWFjY291bnQtdG9rZW4tdDFybGMiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoic3Bpbm5ha2VyLXNlcnZpY2UtYWNjb3VudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6Ijc5MzllMzFjLTQzOTktMTFlOC04NDA4LWZhMTYzZTU3OTE2ZCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OnNwaW5uYWtlci1zZXJ2aWNlLWFjY291bnQifQ.RxtKgxnwfwN8AM3Gp1VAwJI4tFoqExdCn5clDw6UqjO5drl4XjfuKY4gk-n-d_e3M4T1oIC-0rHQqKJR4N-gBKgb2OSO5k8rNkTmMZCZprP4opoQZaf_3NGsxs-po7RmI6J6gKaYKJzKWE_ktpuSKR6nbUKQ2YT29Q5AOaTPVm-o1IvfvWoBVEVnc9mlWnYrpgneWxHkhG9rdQ9IfyS6i4uclnZ0LFH4r5DewO4w4WuZ6OW2LDKeF1JmGcNqGr-Dp6jITCPHa1ZZF9_FlHspqQt4mioQMdm0QsYmw9H-_ry5VKa1gunlLS1q2W8bXgNg6Rk3A2TTFivaKcZa1PS-Qw"
