apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-kubernetes-config
data:
  config: |
    apiVersion: v1
    clusters:
    - cluster:
        server: https://172.16.3.82:6443
       # certificate-authority: /root/.kube/ca.crt
      name: kube01
    contexts:
    - context:
        cluster: kube01
        user: root
      name: kube01
    current-context: kube01
    kind: Config
    preferences: {}
    users:
    - name: root
      user:
       # client-certificate: /root/.kube/apiserver.crt
       # client-key: /root/.kube/apiserver.key
    - name: spinnaker-service-account
      user:
       token: "ZXlKaGJHY2lPaUpTVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUprWldaaGRXeDBJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5elpXTnlaWFF1Ym1GdFpTSTZJbk53YVc1dVlXdGxjaTF6WlhKMmFXTmxMV0ZqWTI5MWJuUXRkRzlyWlc0dGRERnliR01pTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxjblpwWTJVdFlXTmpiM1Z1ZEM1dVlXMWxJam9pYzNCcGJtNWhhMlZ5TFhObGNuWnBZMlV0WVdOamIzVnVkQ0lzSW10MVltVnlibVYwWlhNdWFXOHZjMlZ5ZG1salpXRmpZMjkxYm5RdmMyVnlkbWxqWlMxaFkyTnZkVzUwTG5WcFpDSTZJamM1TXpsbE16RmpMVFF6T1RrdE1URmxPQzA0TkRBNExXWmhNVFl6WlRVM09URTJaQ0lzSW5OMVlpSTZJbk41YzNSbGJUcHpaWEoyYVdObFlXTmpiM1Z1ZERwa1pXWmhkV3gwT25Od2FXNXVZV3RsY2kxelpYSjJhV05sTFdGalkyOTFiblFpZlEuUnh0S2d4bndmd044QU0zR3AxVkF3Skk0dEZvcUV4ZENuNWNsRHc2VXFqTzVkcmw0WGpmdUtZNGdrLW4tZF9lM000VDFvSUMtMHJIUXFLSlI0Ti1nQktnYjJPU081azhyTmtUbU1aQ1pwclA0b3BvUVphZl8zTkdzeHMtcG83Um1JNko2Z0thWUtKektXRV9rdHB1U0tSNm5iVUtRMllUMjlRNUFPYVRQVm0tbzFJdmZ2V29CVkVWbmM5bWxXbllycGduZVd4SGtoRzlyZFE5SWZ5UzZpNHVjbG5aMExGSDRyNURld080dzRXdVo2T1cyTERLZUYxSm1HY05xR3ItRHA2aklUQ1BIYTFaWkY5X0ZsSHNwcVF0NG1pb1FNZG0wUXNZbXc5SC1fcnk1VkthMWd1bmxMUzFxMlc4YlhnTmc2UmszQTJUVEZpdmFLY1phMVBTLVF3" 
