apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-igor
  labels:
    app: {{ template "fullname" . }}
    component: igor
spec:
  ports:
    - port: 8088
      name: igor
    - port: 8080
      name: jenkins-master
  selector:
    app: {{ template "fullname" . }}
    component: igor
